name: idleread
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any
  google_fonts: ^5.1.0
  email_validator: any
  http: any
  url_strategy: any
  firebase_core: any
  firebase_auth: any
  floating_snackbar: any
  flutter_spinkit: any
  flutter_pdfview: ^1.3.2
  file_picker: any
  path: any
  path_provider: any
  syncfusion_flutter_pdfviewer: ^23.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
