// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEksLlXLvm3VBXMD_Pc_uPoHGk8MPuwaQ',
    appId: '1:1038782300793:web:0a68d0b19754d1df7c8aa8',
    messagingSenderId: '1038782300793',
    projectId: 'idleread00',
    authDomain: 'idleread00.firebaseapp.com',
    storageBucket: 'idleread00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX4X1r5SZluw8xv6eQRiMQLOkVbAPzAFg',
    appId: '1:1038782300793:android:2450fb7ba43e08d57c8aa8',
    messagingSenderId: '1038782300793',
    projectId: 'idleread00',
    storageBucket: 'idleread00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH8AGGiitPIbaAJsmP0pSmLGJH5bDIUxo',
    appId: '1:1038782300793:ios:2e6302e593fc885f7c8aa8',
    messagingSenderId: '1038782300793',
    projectId: 'idleread00',
    storageBucket: 'idleread00.appspot.com',
    iosBundleId: 'com.example.idleread',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH8AGGiitPIbaAJsmP0pSmLGJH5bDIUxo',
    appId: '1:1038782300793:ios:ff47cfffeb75da847c8aa8',
    messagingSenderId: '1038782300793',
    projectId: 'idleread00',
    storageBucket: 'idleread00.appspot.com',
    iosBundleId: 'com.example.idleread.RunnerTests',
  );
}
